import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import { OrderFilterProvider } from "@/components/OrderByStatusProvider";
import { OrderInputFilterProvider } from "@/components/OrderFilterProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>


      <body className={inter.className}>
          <OrderFilterProvider>
        <OrderInputFilterProvider>
        {children}
        </OrderInputFilterProvider>
        </OrderFilterProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
